### ISSUE TITLE
添加 cli 和 hub

### ISSUE THREAD

**Issue by xxhg** [linweiyuan/go-chatgpt#2]
你好，可以添加 cli 和 hub 吗？通过浏览器访问。
就像 https://github.com/pengzhile/pandora 一样。

**Comment by linweiyuan** [comment]
cli 没有，有一个 tui
https://github.com/linweiyuan/go-chatgpt（好久没更新有 bug）

不明白 hub 是指什么

如果你的意思是要做网页版，我不会写 CSS，你可以考虑 PR

之前我做这个项目是因为官方网页版动不动就要刷新才能用，很烦，现在不会了，所以我都用官方的网页版，这个项目反而少用了

**Comment by linweiyuan** [comment]
看错了，以为在 go-chatgpt-api 提的 issue

cli 指什么，这种图形化终端不好用吗？

**Comment by linweiyuan** [comment]
我的官方网页版是指 next-chatgpt？

接口调用 go-chatgpt-api，样式抄油管视频

**Comment by xxhg** [comment]
> 我的官方网页版是指 next-chatgpt？
> 
> 接口调用 go-chatgpt-api，样式抄油管视频

next-chatgpt不能登录，
我把 NEXTAUTH_SECRET 设为 ACCESS_TOKEN 也无效，如何使用 ACCESS_TOKEN 啊？

**Comment by linweiyuan** [comment]
不能登录是指？刚试了登录没问题，登录必须设置这个 NEXTAUTH_SECRET，任意值

NEXTAUTH_SECRET 是用来设置 session token 的生成的，不是 ChatGPT 的 access token

**Comment by xxhg** [comment]
> 不能登录是指？刚试了登录没问题，登录必须设置这个 NEXTAUTH_SECRET，任意值
> 
> NEXTAUTH_SECRET 是用来设置 session token 的生成的，不是 ChatGPT 的 access token

好的，谢谢。
